name: Deploy Dockerized Node.js Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # - name: Build and push Docker image
      #   run: |
      #     docker build -t saswath21/my-node-service .
      #     docker tag saswath21/my-node-service saswath21/my-node-service:latest
      #     docker push saswath21/my-node-service:latest

      - name: SSH into the server and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull saswath21/my-node-service:latest
            docker stop my-node-service || true
            docker rm my-node-service || true
            docker run -d -p 3000:3000 --env SECRET_MESSAGE="${{ secrets.SECRET_MESSAGE }}" --env USERNAME="${{ secrets.USERNAME }}" --env PASSWORD="${{ secrets.PASSWORD }}" --name my-node-service saswath21/my-node-service:latest
